# -*- coding: utf-8 -*-
"""
oracoes_eucaristicas.py — Monte Senário

Texto integral (tradução oficial CNBB) das Orações Eucarísticas do Missal
Romano. Fontes:
- I, II, III: https://comshalom.org/oracoes-eucaristicas/
- IV: https://pocketterco.com.br/oracao/oracao-eucaristica-04-iv
  (achada em 18/09/2026 — fecha a última lacuna do projeto: a IGMR n.
  365d indica a IV quando a missa não tem prefácio próprio)

Cobertura: I, II, III e IV — todas as usadas pela regra de sugestão em
sheets_sync.sugerir_oracao_eucaristica() (baseada no n. 365 da IGMR).
Na IV, as variantes opcionais (embolismo alternativo, intercessão
específica de Batismo/Crisma/1ª Comunhão) foram omitidas — só a forma
padrão está incluída, no mesmo padrão de I a III.

A página do comshalom também traz duas fórmulas adicionais (rotuladas
ali como "V" e "VI", mas com texto compatível com as Orações
Eucarísticas para Missas com Crianças/Reconciliação — a numeração do
site não bate com a numeração oficial do Missal). Não foram incluídas
aqui por não se aplicarem à regra de sugestão atual do projeto.

Uso:
    from oracoes_eucaristicas import ORACOES_EUCARISTICAS
    texto = ORACOES_EUCARISTICAS["II"]
"""

ORACOES_EUCARISTICAS = {
    "I": {
        "nome": "Oração Eucarística I (Cânon Romano)",
        "quando_usar": (
            "Domingos e dias com 'Em comunhão' ou 'Recebei, ó Pai' "
            "próprios; festas de Apóstolos e Santos citados no Cânon "
            "(IGMR n. 365a)."
        ),
        "texto": (
            "Pai de misericórdia, a quem sobem nossos louvores, "
            "suplicantes, vos rogamos e pedimos por Jesus Cristo, vosso "
            "Filho e Senhor nosso, que aceiteis e abençoeis \u2020 estes "
            "dons, estas oferendas, este sacrifício puro e santo, que "
            "oferecemos, antes de tudo, pela vossa Igreja santa e "
            "católica: concedei-lhe paz e proteção, unindo-a num só "
            "corpo e governando-a por toda a terra, em comunhão com o "
            "vosso servo o Papa N., o nosso Bispo N., e todos os que "
            "guardam a fé católica que receberam dos Apóstolos.\n"
            "AS: Abençoai nossa oferenda, ó Senhor!\n\n"
            "Lembrai-vos, ó Pai, dos vossos filhos e filhas N. N. e de "
            "todos os que circundam este altar, dos quais conheceis a "
            "fé e a dedicação ao vosso serviço. Por eles nós vos "
            "oferecemos e também eles vos oferecem este sacrifício de "
            "louvor por si e por todos os seus, e elevam a vós as suas "
            "preces, Deus eterno, vivo e verdadeiro, para alcançar o "
            "perdão de suas faltas, a segurança em suas vidas e a "
            "salvação que esperam.\n"
            "AS: Lembrai-vos, ó Pai, de vossos filhos!\n\n"
            "Em comunhão com toda a Igreja, celebramos em primeiro "
            "lugar a memória da Mãe de nosso Deus e Senhor Jesus "
            "Cristo, a gloriosa sempre Virgem Maria, a de seu esposo "
            "São José, e também a dos Santos Apóstolos e Mártires: "
            "Pedro e Paulo, André, (Tiago e João, Tomé, Tiago e Filipe, "
            "Bartolomeu e Mateus, Simão e Tadeu, Lino, Cleto, Clemente, "
            "Sisto, Cornélio e Cipriano, Lourenço e Crisógono, João e "
            "Paulo, Cosme e Damião), e todos os vossos Santos. Por seus "
            "méritos e preces concedei-nos sem cessar a vossa proteção. "
            "(Por Cristo, nosso Senhor. Amém).\n"
            "AS: Em comunhão com os vossos Santos vos louvamos!\n\n"
            "Dignai-vos, ó Pai, aceitar, abençoar e santificar estas "
            "oferendas, recebei-as como sacrifício espiritual perfeito, "
            "a fim de que se tornem para nós o Corpo e \u2020 o Sangue "
            "de vosso amado Filho, nosso Senhor Jesus Cristo.\n"
            "AS: Enviai o vosso Espírito Santo!\n\n"
            "Na véspera de sua paixão, ele tomou o pão em suas santas e "
            "veneráveis mãos, elevou os olhos ao céu, a vós, ó Pai, "
            "todo-poderoso, pronunciou a bênção de ação de graças, "
            "partiu o pão e o deu a seus discípulos, dizendo:\n"
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ "
            "ENTREGUE POR VÓS.\n\n"
            "Do mesmo modo, ao fim da Ceia, ele tomou este precioso "
            "cálice em suas santas e veneráveis mãos, pronunciou "
            "novamente a bênção de ação de graças e o deu a seus "
            "discípulos, dizendo:\n"
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O "
            "SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR "
            "VÓS E POR TODOS, PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM "
            "MEMÓRIA DE MIM.\n"
            "Mistério da fé!\n"
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a "
            "vossa ressurreição. Vinde, Senhor Jesus!\n\n"
            "Celebrando, pois, a memória da bem-aventurada paixão do "
            "vosso Filho, da sua ressurreição dentre os mortos e "
            "gloriosa ascensão aos céus, nós, vossos servos, e também "
            "vosso povo santo, vos oferecemos, ó Pai, dentre os bens "
            "que nos destes, o sacrifício puro, santo e imaculado, Pão "
            "santo da vida eterna e Cálice da perpétua salvação.\n\n"
            "Recebei, ó Pai, com olhar benigno, esta oferta, como "
            "recebestes os dons do justo Abel, o sacrifício de nosso "
            "patriarca Abraão e a oblação pura e santa do sumo "
            "sacerdote Melquisedeque.\n"
            "AS: Aceitai, ó Senhor, a nossa oferta!\n\n"
            "Suplicantes, vos pedimos, ó Deus onipotente, que esta "
            "nossa oferenda seja levada à vossa presença, no altar do "
            "céu, pelas mãos do vosso santo Anjo, para que todos nós, "
            "participando deste altar, pela comunhão do santíssimo "
            "Corpo e Sangue do vosso Filho, sejamos repletos de todas "
            "as graças e bênçãos do céu. (Por Cristo, nosso Senhor. "
            "Amém)\n"
            "AS: O Espírito nos una num só corpo!\n\n"
            "Lembrai-vos, ó Pai, dos vossos filhos e filhas N. N. que "
            "nos precederam com o sinal da fé e dormem o sono da paz. "
            "A eles, e a todos os que descansam no Cristo, concedei o "
            "repouso, a luz e a paz. (Por Cristo, nosso Senhor. Amém)\n"
            "AS: Concedei-lhes, ó Senhor, a luz eterna!\n\n"
            "E a todos nós pecadores, que esperamos na vossa infinita "
            "misericórdia, concedei, não por nossos méritos, mas por "
            "vossa bondade, o convívio dos Apóstolos e Mártires: João "
            "Batista e Estêvão, Matias e Barnabé, (Inácio, Alexandre, "
            "Marcelino e Pedro, Felicidade e Perpétua, Águeda e Luzia, "
            "Inês, Cecília, Anastácia) e de todos os vossos Santos. Por "
            "Cristo, nosso Senhor.\n\n"
            "Por ele não cessais de criar e santificar, vivificar, "
            "abençoar estes bens e distribuí-los entre nós.\n\n"
            "Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai "
            "todo-poderoso, na unidade do Espírito Santo, toda a honra "
            "e toda a glória, por todos os séculos dos séculos.\n"
            "AS: Amém."
        ),
    },
    "II": {
        "nome": "Oração Eucarística II",
        "quando_usar": (
            "Dias de semana ou circunstâncias especiais; tem prefácio "
            "próprio, mas aceita outros prefácios sucintos (IGMR n. 365b)."
        ),
        "texto": (
            "Na verdade, é digno e justo, é nosso dever e salvação "
            "dar-vos graças sempre e em todo o lugar, Senhor, Pai "
            "santo, por vosso amado Filho, Jesus Cristo. Ele é a vossa "
            "Palavra, pela qual tudo criastes. Ele é o nosso Salvador e "
            "Redentor, que se encarnou pelo Espírito Santo e nasceu da "
            "Virgem Maria. Ele, para cumprir a vossa vontade e adquirir "
            "para vós um povo santo, estendeu os braços na hora da sua "
            "paixão, a fim de vencer a morte e manifestar a "
            "ressurreição. Por isso, com os Anjos e todos os Santos, "
            "proclamamos vossa glória, cantando (dizendo) a uma só "
            "voz:\n"
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e "
            "a terra proclamam a vossa glória. Hosana nas alturas! "
            "Bendito o que vem em nome do Senhor! Hosana nas alturas!\n\n"
            "Na verdade, ó Pai, vós sois Santo, fonte de toda "
            "santidade. Santificai, pois, estes dons, derramando sobre "
            "eles o vosso Espírito, a fim de que se tornem para nós o "
            "Corpo e \u2020 o Sangue de nosso Senhor Jesus Cristo.\n"
            "AS: Enviai o Vosso Espírito Santo!\n\n"
            "Estando para ser entregue e abraçando livremente a "
            "paixão, Jesus tomou o pão, pronunciou a bênção de ação de "
            "graças, partiu e o deu a seus discípulos, dizendo:\n"
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ "
            "ENTREGUE POR VÓS.\n\n"
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas "
            "mãos e, dando graças novamente, o entregou a seus "
            "discípulos, dizendo:\n"
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O "
            "SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR "
            "VÓS E POR TODOS, PARA A REMISSÃO DOS PECADOS. FAZEI ISTO "
            "EM MEMÓRIA DE MIM.\n"
            "Mistério da fé!\n"
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a "
            "vossa ressurreição. Vinde, Senhor Jesus!\n\n"
            "Celebrando, pois, o memorial da morte e ressurreição do "
            "vosso Filho, nós vos oferecemos, ó Pai, o Pão da vida e o "
            "Cálice da salvação; e vos agradecemos porque nos "
            "tornastes dignos de estar aqui na vossa presença e vos "
            "servir.\n"
            "AS: Aceitai, ó Senhor, a nossa oferta!\n\n"
            "Suplicantes, vos pedimos que, participando do Corpo e "
            "Sangue de Cristo, sejamos reunidos pelo Espírito Santo num "
            "só corpo.\n"
            "AS: O Espírito nos una num só corpo!\n\n"
            "Lembrai-vos, ó Pai, da vossa Igreja que se faz presente "
            "pelo mundo inteiro; que ela cresça na caridade, em "
            "comunhão com o papa N., com o nosso bispo N., os bispos do "
            "mundo inteiro, os presbíteros, os diáconos e todos os "
            "ministros do vosso povo.\n"
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!\n\n"
            "Lembrai-vos também, na vossa misericórdia, dos (outros) "
            "nossos irmãos e irmãs que adormeceram na esperança da "
            "ressurreição e de todos os que partiram desta vida; "
            "acolhei-os junto a vós na luz da vossa face.\n"
            "AS: Concedei-lhes, ó Senhor, a luz eterna!\n\n"
            "Enfim, nós vos pedimos, tende piedade de todos nós e "
            "dai-nos participar da vida eterna, com a Virgem Maria, Mãe "
            "de Deus, São José, seu esposo, os Apóstolos e todos os "
            "Santos que neste mundo viveram na vossa amizade, a fim de "
            "vos louvarmos e glorificarmos por Jesus Cristo, vosso "
            "Filho.\n\n"
            "Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai "
            "todo-poderoso, na unidade do Espírito Santo, toda a honra "
            "e toda a glória, por todos os séculos dos séculos.\n"
            "AS: Amém!"
        ),
    },
    "III": {
        "nome": "Oração Eucarística III",
        "quando_usar": (
            "Aceita qualquer prefácio — preferida aos domingos e "
            "festas (IGMR n. 365c)."
        ),
        "texto": (
            "Na verdade, vós sois Santo, ó Deus do universo, e tudo o "
            "que criastes proclama o vosso louvor, porque, por Jesus "
            "Cristo, vosso Filho e Senhor nosso, e pela força do "
            "Espírito Santo, dais vida e santidade a todas as coisas e "
            "não cessais de reunir para vós um povo que vos ofereça em "
            "toda parte, do nascer ao pôr do sol, um sacrifício "
            "perfeito.\n\n"
            "Por isso, ó Pai, nós vos suplicamos: santificai pelo "
            "Espírito Santo as oferendas que vos apresentamos para "
            "serem consagradas a fim de que se tornem o Corpo \u2020 e "
            "o Sangue de vosso Filho, nosso Senhor Jesus Cristo, que "
            "nos mandou celebrar estes mistérios.\n"
            "AS: Enviai o vosso Espírito Santo!\n\n"
            "Na noite em que ia ser entregue, Jesus tomou o pão, "
            "pronunciou a bênção de ação de graças, partiu e o deu a "
            "seus discípulos, dizendo:\n"
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ "
            "ENTREGUE POR VÓS.\n\n"
            "Do mesmo modo, ao fim da Ceia, ele tomou o cálice em suas "
            "mãos, pronunciou a bênção de ação de graças, e o deu a "
            "seus discípulos, dizendo:\n"
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O "
            "SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR "
            "VÓS E POR TODOS, PARA A REMISSÃO DOS PECADOS. FAZEI ISTO "
            "EM MEMÓRIA DE MIM.\n"
            "Mistério da fé!\n"
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a "
            "vossa ressurreição. Vinde, Senhor Jesus!\n\n"
            "Celebrando agora, ó Pai, o memorial da paixão redentora do "
            "vosso Filho, da sua gloriosa ressurreição e ascensão ao "
            "céu, e enquanto esperamos sua nova vinda, nós vos "
            "oferecemos em ação de graças este sacrifício vivo e "
            "santo.\n"
            "AS: Aceitai, ó Senhor, a nossa oferta!\n\n"
            "Olhai com bondade a oblação da vossa Igreja e reconhecei "
            "nela o sacrifício que nos reconciliou convosco; concedei "
            "que, alimentando-nos com o Corpo e o Sangue do vosso "
            "Filho, repletos do Espírito Santo, nos tornemos em Cristo "
            "um só corpo e um só espírito.\n"
            "AS: O Espírito nos una num só corpo!\n\n"
            "Que o mesmo Espírito faça de nós uma eterna oferenda para "
            "alcançarmos a herança com os vossos eleitos: a santíssima "
            "Virgem Maria, Mãe de Deus, São José, seu esposo, os "
            "vossos santos Apóstolos e gloriosos Mártires, N. (Santo do "
            "dia ou padroeiro) e todos os Santos, que não cessam de "
            "interceder por nós na vossa presença.\n"
            "AS: Fazei de nós uma perfeita oferenda!\n\n"
            "Nós vos suplicamos, Senhor, que este sacrifício da nossa "
            "reconciliação estenda a paz e a salvação ao mundo inteiro. "
            "Confirmai na fé e na caridade a vossa Igreja que caminha "
            "neste mundo com o vosso servo o Papa N., e o nosso Bispo "
            "N., com os bispos do mundo inteiro, os presbíteros e "
            "diáconos, os outros ministros e o povo por vós redimido. "
            "Atendei propício às preces desta família, que reunistes em "
            "vossa presença. Reconduzi a vós, Pai de misericórdia, "
            "todos os vossos filhos e filhas dispersos pelo mundo "
            "inteiro.\n"
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!\n\n"
            "Acolhei com bondade no vosso reino os nossos irmãos e "
            "irmãs que partiram desta vida e todos os que morreram na "
            "vossa amizade. Unidos a eles, esperamos também nós "
            "saciar-nos eternamente da vossa glória, por Cristo, "
            "Senhor nosso. Por ele dais ao mundo todo bem e toda "
            "graça.\n\n"
            "Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai "
            "todo-poderoso, na unidade do Espírito Santo, toda honra e "
            "toda glória, por todos os séculos dos séculos.\n"
            "AS: Amém!"
        ),
    },
    "IV": {
        "nome": "Oração Eucarística IV",
        "quando_usar": (
            "Tem prefácio fixo, que resume a história da salvação e não "
            "pode ser trocado — por isso só se usa quando a missa não "
            "tem prefácio próprio (IGMR n. 365d). Fonte: "
            "pocketterco.com.br (Textos Litúrgicos © CNBB)."
        ),
        "texto": (
            "Na verdade, ó Pai, é nosso dever dar-vos graças, é nossa "
            "salvação dar-vos glória. Só vós sois o Deus vivo e "
            "verdadeiro que existis antes de todo o tempo e permaneceis "
            "para sempre, habitando em luz inacessível.\n\n"
            "Mas, porque sois o Deus de bondade e a fonte da vida, "
            "fizestes todas as coisas para cobrir de bênçãos as vossas "
            "criaturas e a muitos alegrar com o esplendor da vossa luz.\n\n"
            "Eis, pois, diante de vós os inumeráveis coros dos Anjos que "
            "dia e noite vos servem e, contemplando a glória da vossa "
            "face, vos louvam sem cessar. Com eles também nós e, por "
            "nossa voz, tudo o que criastes celebramos vosso Nome e, "
            "exultantes de alegria, cantamos (dizemos) a uma só voz:\n"
            "AS: Santo, Santo, Santo, Senhor Deus do universo. O céu e "
            "a terra proclamam a vossa glória. Hosana nas alturas! "
            "Bendito o que vem em nome do Senhor! Hosana nas alturas!\n\n"
            "Nós proclamamos vossa grandeza, Pai santo, a sabedoria e o "
            "amor com que fizestes todas as coisas. Criastes o ser "
            "humano à vossa imagem e lhe confiastes todo o universo, "
            "para que, servindo somente a vós, seu Criador, cuidasse de "
            "toda criatura. E quando pela desobediência perdeu a vossa "
            "amizade, não o abandonastes ao poder da morte. A todos, "
            "porém, socorrestes com misericórdia, para que, ao "
            "procurar-vos, vos encontrassem. Muitas vezes oferecestes "
            "aliança à família humana e a instruístes pelos profetas na "
            "esperança da salvação.\n"
            "AS: A todos socorrestes com bondade!\n\n"
            "E de tal modo, Pai santo, amastes o mundo que, chegada a "
            "plenitude dos tempos, nos enviastes vosso próprio Filho "
            "para ser o nosso Salvador. Encarnado pelo poder do "
            "Espírito Santo e nascido da Virgem Maria, Jesus viveu em "
            "tudo a condição humana, menos o pecado; anunciou aos "
            "pobres a salvação, aos oprimidos, a liberdade, aos "
            "tristes, a alegria. Para cumprir o vosso plano de amor, "
            "entregou-se à morte e, ressuscitando, destruiu a morte e "
            "renovou a vida.\n"
            "AS: Por amor nos enviastes vosso Filho!\n\n"
            "E, a fim de não mais vivermos para nós, mas para ele, que "
            "por nós morreu e ressuscitou, enviou de vós, ó Pai, como "
            "primeiro dom aos vossos fiéis, o Espírito Santo, que "
            "continua sua obra no mundo para levar à plenitude toda a "
            "santificação.\n\n"
            "Por isso, nós vos pedimos, ó Pai, que o mesmo Espírito "
            "Santo santifique estas oferendas, a fim de que se tornem o "
            "Corpo e \u2020 o Sangue de Jesus Cristo, vosso Filho e "
            "Senhor nosso, para celebrarmos este grande mistério que "
            "ele nos deixou em sinal da eterna aliança.\n"
            "AS: Enviai o vosso Espírito Santo!\n\n"
            "Quando, pois, chegou a hora em que por vós, ó Pai, ia ser "
            "glorificado, tendo amado os seus que estavam no mundo, "
            "amou-os até o fim. Enquanto ceavam, Jesus tomou o pão, "
            "pronunciou a bênção de ação de graças, partiu e o deu a "
            "seus discípulos, dizendo:\n"
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ "
            "ENTREGUE POR VÓS.\n\n"
            "Do mesmo modo, ele tomou em suas mãos o cálice com vinho, "
            "deu-vos graças novamente, e o deu a seus discípulos, "
            "dizendo:\n"
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O "
            "SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR "
            "VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM "
            "MEMÓRIA DE MIM.\n"
            "Mistério da fé!\n"
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a "
            "vossa ressurreição. Vinde, Senhor Jesus!\n\n"
            "Celebrando, agora, ó Pai, o memorial da nossa redenção, "
            "anunciamos a morte de Cristo e sua descida entre os "
            "mortos, proclamamos a sua ressurreição e ascensão à vossa "
            "direita e, esperando a sua vinda gloriosa, nós vos "
            "oferecemos o seu Corpo e Sangue, sacrifício do vosso "
            "agrado e salvação para o mundo inteiro.\n"
            "AS: Aceitai, ó Senhor, a nossa oferta!\n\n"
            "Olhai, com bondade, a oblação que destes à vossa Igreja e "
            "concedei aos que vamos participar do mesmo pão e do mesmo "
            "cálice que, reunidos pelo Espírito Santo num só corpo, nos "
            "tornemos em Cristo uma oferenda viva para o louvor da "
            "vossa glória.\n"
            "AS: O Espírito nos una num só corpo!\n\n"
            "E agora, ó Pai, lembrai-vos de todos pelos quais vos "
            "oferecemos este sacrifício: o vosso servo o Papa N., o "
            "nosso Bispo N., os bispos do mundo inteiro, os "
            "presbíteros, os diáconos, e todos os ministros da vossa "
            "Igreja, os fiéis que, ao redor deste altar, se unem à "
            "nossa oferta, o povo que vos pertence e aqueles que vos "
            "procuram de coração sincero.\n"
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!\n\n"
            "Lembrai-vos também dos que morreram na paz do vosso Cristo "
            "e de todos os defuntos dos quais só vós conhecestes a fé.\n"
            "AS: Concedei-lhes, ó Senhor, a luz eterna!\n\n"
            "E a todos nós, vossos filhos e filhas, concedei, ó Pai de "
            "bondade, alcançar a herança eterna, com a Virgem Maria, "
            "Mãe de Deus, São José, seu esposo, os Apóstolos e todos os "
            "Santos, no vosso reino, onde, com todas as criaturas, "
            "libertas da corrupção do pecado e da morte, vos "
            "glorificaremos, por Cristo, Senhor nosso, por quem dais ao "
            "mundo todo bem e toda graça.\n\n"
            "Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai "
            "todo-poderoso, na unidade do Espírito Santo, toda honra e "
            "toda glória, por todos os séculos dos séculos.\n"
            "AS: Amém."
        ),
    },
}

FONTE = "https://comshalom.org/oracoes-eucaristicas/ (I, II, III); https://pocketterco.com.br (IV)"


def obter_oracao(numeral: str) -> dict | None:
    """numeral: 'I', 'II' ou 'III'. Retorna None para 'IV' (não disponível
    nesta fonte) ou numeral inválido."""
    return ORACOES_EUCARISTICAS.get(numeral.upper())
